### ISSUE TITLE
THREE.WebGLRenderer: Context Lost. model-viewer.js:24938

### ISSUE THREAD

**Issue by motadon-atharva** [google/model-viewer#2307] opened 2021-04-21 06:36 UTC
### Description

Hi, I have suddenly found this problem affecting the loading of 3D models since past 2-3 days. There are many js errors and warnings that have popped up.
- THREE.WebGLRenderer: Context Lost. model-viewer.js:24938
- WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
- [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
- [Violation] Forced reflow while executing JavaScript took 36ms

I have no idea if it is something that I am doing wrong or something has changed in the js files.

#### Live Demo
https://kloud.care/product/tpe-kit-1/
![Capture](https://user-images.githubusercontent.com/60126100/115507605-f6d85200-a299-11eb-8d6f-d8125e06d5df.JPG)

### Version
https://unpkg.com/@google/model-viewer@1.6.0/dist/model-viewer.min.js
- model-viewer: vX.X.X

### Browser Affected
- [-] Chrome, version: 90.0.4430.72
- [-] Edge
- [-] Firefox
- [-] IE
- [-] Safari

### OS
- [-] Android
- [-] iOS
- [ ] Linux
- [-] MacOS
- [-] Windows

**Comment by elalish** [comment] 2021-04-22 16:26
I don't see model-viewer on your link, nor any of the errors you see. The non-passive event listener is known, but it's a Chrome bug that it's being raised at all in this case. The reflow warning is a normal page optimization opportunity. The context lost error is a problem. Are you really seeing this on every browser and OS combination you've listed here? I'm going to need some specifics and a link where I can repro the problem.

**Comment by nthnmillar** [comment] 2021-04-27 07:52
<img width="613" alt="AR-context-lost" src="https://user-images.githubusercontent.com/15206335/116205112-c3596400-a780-11eb-95f9-9a84cd5db9f6.png">

Hi, I'm also getting the context lost error. The ar works fine from the model-viewer in my local dev environment, whereas the built version of the site hosted online logs the above errors and the ar crashes.

**Comment by elalish** [comment] 2021-04-27 16:08
@nthnmillar Can you post a link so I can repro? I don't see a context lost error in your screenshot. There's a three.js API change warning, but I've recently fixed that (and it's not an error yet). 

Out of curiosity, what are you using Three.js for separately from model-viewer? You can find the three.js version used for a given model-viewer version on our releases: https://github.com/google/model-viewer/releases

**Comment by nthnmillar** [comment] 2021-04-28 03:45
Unfortunately, it's for a client so I can't share it publicly. Sorry I confused the three message '.context has been removed'. with context lost.

I tried installing the dependency @google/model-viewer directly into my dev environment to see if I could find the cause of the three.js .context error or see if the local code would build correctly. I then created a new model-viewer element with the following advice:

https://github.com/google/model-viewer/issues/1054

The reason for the separate 3d scene is because it has additional 3d content and functionality which doesn't get augmented. I also changed the three.js version for the 3d scene to the one used in model-viewer. but the ar session from the model-viewer element I created still returns the same error.  It's almost as if .content is used in the built site somewhere instead of getContext(), the ar works fine from the localhost though.

<img width="717" alt="Screen Shot 2021-04-28 at 1 27 05 pm" src="https://user-images.githubusercontent.com/15206335/116343044-01a95e80-a827-11eb-834a-d2ba78654fa9.png">

**Comment by elalish** [comment] 2021-05-03 15:35
Again, that's just a warning; it hasn't actually stopped working yet, but will in a future version of three.js. So your problem is unrelated. I'll need you to build some kind of minimal repro for me that doesn't involve your client's data so I can see what the problem is.

**Comment by nthnmillar** [comment] 2021-05-03 22:06
It fine I've resolved the issue thanks.

**Comment by elalish** [comment] 2021-05-03 23:41
@motadon-atharva I'm closing this since I can't reproduce with the link provided. Let us know if you're still having trouble.

**Closed by elalish** 2021-05-03 23:41 UTC

**Comment by pfortes** [comment] 2021-07-07 21:13
![Multiple instances of three.js being imported ](https://user-images.githubusercontent.com/782464/124829301-14829280-df3e-11eb-85da-e334f4f02068.png)


Hello @nthnmillar and @elalish, did you get a solution for avoiding loading three two times when using model-viewer inside a project that also has other 3d stuff going on?

I have tried locking the three versions to the same one, also tried yarn resolutions, but i keep getting the "Multiple instances of Three.js being imported." warning and if i analyze my bundle i have like 770k for model-viewer and 600k for three.module.js

tnx

**Comment by elalish** [comment] 2021-07-07 21:24
No, considering that MV is higher-level than three, we didn't expect many devs to be using both. I believe it's possible to use the three.js version that's already built into MV for other things, but I'm not sure how that'll fit into your specific build pipeline. What are you trying to accomplish?

**Comment by nthnmillar** [comment] 2021-07-07 22:45
My issue was caused by the model viewer needing to be set up correctly but still received the warning unfortunately.

**Comment by pfortes** [comment] 2021-07-07 23:02
> No, considering that MV is higher-level than three, we didn't expect many devs to be using both. I believe it's possible to use the three.js version that's already built into MV for other things, but I'm not sure how that'll fit into your specific build pipeline. What are you trying to accomplish?

Thank you for answering.

You can see a working example of what i am building at [http://ar.visualma.com/](http://ar.visualma.com/) 
(the model viewer AR button only apears if you see it with a phone or XR compatible device)

I am using three.js to create a webGL scene that displays a animated slideshow with some 3d models, this part of the app is not using model viewer because it uses some special camera control, post-processing, etc.

i use model-viewer to add AR functionality to each of the models when the device of the user is compatible (i use the reveal="manual" prop to have only the AR button and not the viewer in the scene)

i would love to try doing something like what you mention about of using the three version that is already build into MV because even if i am loading MB's of gltf models it realy feels wierd/evil importing three two times..

**Comment by elalish** [comment] 2021-07-08 16:09
@pfortes Thanks for the example, that's cool! I'll look into this further, but it may be a little while.

**Comment by pfortes** [comment] 2021-07-08 18:28
Great, thanks!
