### ISSUE TITLE
Ar-scale="fixed" not working on iOS Chrome

### ISSUE THREAD

**Issue by Aubi0ne** [google/model-viewer#1857] opened 2021-01-21 12:14 UTC
### Description

Hello,

I'd like to set ar-scale option to "fixed" and it works fine on all platforms except on iOs Chrome. Is this normal ? Or is there an option to add for this version?

#### Live Demo

My current model-viewer setup :
<model-viewer
            ar
            exposure="0.5"
            ar-placement="wall"
            ar-scale="fixed"
            camera-controls
            alt="A 3D model of some wall art"
            id="model-viewer"
\>

### Version

- model-viewer: v1.4.1

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment] 2021-01-21 19:45
Closing this as a duplicate of #1719. Looks like an iOS Chrome bug.

**Closed by elalish** 2021-01-21 19:45 UTC
