### ISSUE TITLE
Performance Problems since version 0.7.0

### ISSUE THREAD

**Issue by freinbichler** [google/model-viewer#872] opened 2019-11-04 16:42 UTC
### Description
Since upgrading to version 0.7.0, animation and scroll handler performance on the whole website degraded in desktop Safari (version 13.0.3). After downgrading to version 0.6.2, performance was back to normal. I only see these issues in desktop Safari, Safari on iOS and iPadOS work fine.

#### Live Demo
https://amadeus.design/en/for-architects/ (problem fixed on the production site by setting `interaction-prompt-style` to basic)
Try to open the menu, while the 3D model is in view. Interestingly, as soon as you interact with the model, everything works fine again.

### Browser Affected
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari 13.0.3

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS 10.14.6
- [ ] Windows

### Versions

- model-viewer: v0.7.0 - v0.7.2 (via unpkg)

**Comment by cdata** [comment] 2019-11-04 17:35
Thanks for reporting this @freinbichler 

Without having investigated it, I will concur that there seems to be some subjective performance degradation in recent versions. We'll look into this more deeply.

**Comment by cdata** [comment] 2019-11-04 17:37
@freinbichler if you configure `<model-viewer>` with `interaction-prompt-style="basic"`, do you still experience the performance issues?

**Comment by freinbichler** [comment] 2019-11-05 11:58
@cdata sorry for the late response, could only test this now. `interaction-prompt-style="basic"` indeed fixes the performance problems. So the new "wiggling" default may be the culprit. Thank you for looking into this!

**Comment by elalish** [comment] 2020-03-11 00:29
Sounds like this was resolved, and we also removed the animated SVG that was the cause of many performance issues, so closing.

**Closed by elalish** 2020-03-11 00:29 UTC
Labels: arc: community, arc: compatibility, arc: performance, type: bug
