### ISSUE TITLE
Ar button does not appear in Instagram's web browser (ios)

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#2322] opened 2021-04-24 17:38 UTC
Hello all!

When you open model-viewer in instagram's web browser ar-button does not appear on ios devices. On Android there is no problem.

What can we do about this issue? or is it instagram's ios policy about third party applications.

ps: also in linkedin's web browser same thing but on twitter's web browser ar-button appears and working fine.

-->
- model-viewer: v1.6

**Comment by sercandemirtas** [comment] 2021-04-25 12:05
In addition; what type of web browser we have to add on ios or android application to see model-viewer and ar-button.

**Comment by canberka** [comment] 2021-04-25 13:17
> Hello all!
> 
> When you open model-viewer in instagram's web browser ar-button does not appear on ios devices. On Android there is no problem.
> 
> What can we do about this issue? or is it instagram's ios policy about third party applications.
> 
> ps: also in linkedin's web browser same thing but on twitter's web browser ar-button appears and working fine.
> 
> -->
> 
> * model-viewer: v1.6

we tried that on android and ios.. This is what exactly you said. Androids work well, but on ios there is no model button at instagram's and linkedln's browser. All problems come with ios. 

@elalish this should be very usefull for users where comes from instagram and linkedln.

**Comment by elalish** [comment] 2021-04-26 17:32
@tpsiaki @AdrianAtGoogle Is there anything we can do to get these webview-type browsers working for AR?

**Comment by ryancrunchi** [comment] 2021-04-27 07:43
duplicate of https://github.com/google/model-viewer/issues/1511

**Comment by elalish** [comment] 2021-04-27 16:02
Yes, let's consolidate this discussion here: https://github.com/google/model-viewer/discussions/1915

**Closed by elalish** 2021-04-27 16:02 UTC
