### ISSUE TITLE
safari artifact issue

### ISSUE THREAD

**Issue by DusanMilko** [google/model-viewer#4773] opened 2024-05-14 19:08 UTC
### Description
Seeing artifacts in safari 17.2.1

<img width="970" alt="Screenshot 2024-05-14 at 2 05 42 PM" src="https://github.com/google/model-viewer/assets/302239/c4032496-657d-4a8d-9cad-98cb619737c8">

#### Live Demo
https://modelviewer.dev/editor/

### Version
Latest

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment] 2024-05-15 17:25
Oh, I'm on Safari 17.4.1 - does updating help? Might just be a driver bug.

**Comment by elalish** [comment] 2024-05-30 20:27
Would you mind filing a bug on WebKit then?

**Comment by cpiggott** [comment] 2024-09-03 18:18
@elalish 

I'm having the same issue on the latest version of Chrome(128.0.6613.113) on MacOS Sonoma(14.6.1). I don't see the issue happening in older version of 
Intel based MBP from 2019. AMD Radeon Pro 5500M(4GB) and Intel UHD 630. 

Video is attached as well as PC specs.

<img width="233" alt="Screenshot 2024-09-03 at 1 12 07 PM" src="https://github.com/user-attachments/assets/421de53a-e4e5-4f65-90ec-be78b7e24353">

https://github.com/user-attachments/assets/117fb748-1a9c-4fcc-a5bc-11c2701015bf

![Screenshot 2024-09-03 at 1 18 27 PM](https://github.com/user-attachments/assets/f9f55158-904d-451f-8b8b-4a0f8dcd8068)

**Comment by elalish** [comment] 2024-09-04 15:54
FYI @mrdoob @mugen Looks like there was a regression in a Three.js shader sometime between r160 and r163 for Intel/AMD Macbook pros. Maybe related to `texture2DGradEXT` - I'd look into it, but I don't have a machine that can repro it. Can anyone else repro? Ideally also in some of the Three.js glTF examples?

**Comment by mrdoob** [comment] 2024-09-05 05:08
Is there a live demo to test?

**Comment by elalish** [comment] 2024-09-05 15:50
@mrdoob Yes, the screenshots above are from https://modelviewer.dev/editor/ using Damaged Helmet or Boom Box from the select model drop-down.

**Comment by elalish** [comment] 2024-09-13 22:14
As best we can tell this is a GPU driver bug on older Macs that would only be resolvable by making some kind of shader work-around in three.js. This does not appear to be a wide-spread enough issue to warrant that kind of effort. I'm going to close this for now; if someone really wants to follow up, I'd recommend filing an issue on Three.js with a minimal repro - ideally one of the Three.js glTF examples.

**Closed by elalish** 2024-09-13 22:14 UTC

**Comment by mrdoob** [comment] 2024-09-14 01:48
This should be reported to Apple and not to Three.js 🙏

**Comment by cpiggott** [comment] 2024-09-17 15:14
@mrdoob @elalish Would you mind pointing me in the direction of where to report to Apple. 

We've had multiple people report this issue now to us directly. We were able to repro with r163.
