### ISSUE TITLE
Why is working in some Androids devices and others no?

### ISSUE THREAD

**Issue by Wulff2099** [google/model-viewer#1460] opened 2020-08-14 18:38 UTC
https://virtualdesign.es/projects/fontenla/test/packages/modelviewer.dev/examples/color42.html

I create this page where it change the colour of a sofa.
In pc is working fine, but in android to some persons are working and some persons are not working, all run the model on chrome. 
and i dont have any idea what is the problem

**Comment by elalish** [comment] 2020-08-14 19:02
When you say "not working", can you be more specific? Are you saying the model doesn't load at all, or just the changing colors part doesn't work? Or is changing colors only not working in AR mode? My first question is what device and browser version are you seeing this on? If you can get any console logs, that would also be helpful.

**Comment by Wulff2099** [comment] 2020-08-14 19:56
My device is an samsunf S7 with chrome and is working the other is samsung S9 with chrome and not working.
The problem is that when press the icon of AR it ask to acces the camera press ok and nothing happens. 
The camera do not open and not show the AR in the environment. I can t send you the log because is a friends phone. If you need more specification please tell me.

**Comment by elalish** [comment] 2020-08-14 20:31
Ah, so it's just entering AR that's not working. Okay, can you test `ar-modes="scene-viewer"` vs `ar-modes="webxr"` and tell me if the results are different? And can you verify the chrome version you are each using? WebXR is new, so if Chrome is not up to date, that could easily explain it.

**Comment by Wulff2099** [comment] 2020-08-14 20:33
I will test it and i send a feed back with this new code. 
Thax

**Comment by FrankHiguera** [comment] 2020-08-15 12:49
Hello I wanted to contribute with some similar symptoms that my development presents, 3 days ago my development based on (model-viewer v1.1) worked correctly on Android and iPhone. (Note: I had webxr as the first ar-mode ), well a couple of days ago it stopped working only on adroid (I tried on my s7 and s9 devices in crhome and samsung browser where it was already working in the past and I experience waht Wulff2099 describerd) and when I changed the order of ar-modes = "scene-viewer webxr ..." works again, I think the problem will be in WEBXR only in android, but most likely it is realted to an update on the device (browser or OS) that affected model-viewer.

**Comment by elalish** [comment] 2020-08-17 15:11
@FrankHiguera Thank you for the head's up! Can you give me any more details on what went wrong with WebXR? Do you see any console logs when you connect to your phone with chrome://inspect/#devices? I also work on the Chrome WebXR team, so I'm the right person to get these bugs fixed as well.

**Comment by elalish** [comment] 2020-08-17 20:52
Okay, it looks like this was an ARCore update that broke us; it had only partially rolled out, which I think is why some devices were working and others weren't. We've let them know and I believe it's now getting rolled back while we figure out the issue. If you have Play Services for AR v1.18, you should be fine, v1.19 seems to be problematic. Please let me know if you are still having problems or if your results don't match my description here. Thanks for the bug reports!

**Comment by Wulff2099** [comment] 2020-08-18 14:26
Hi all thanks for all the help.
Where i need to change this ar-modes="scene-viewer" vs ar-modes="webxr"?
mi code is this one. 
   <model-viewer src="assets/sillon03.glb"
                  ios-src="assets/sillon01.usdz"
                  alt="Zapatillas negras tornasol"
                  shadow-intensity="1"
                  camera-controls
                  interaction-prompt="auto"
                  quick-look-browsers="safari chrome"
                  auto-rotate ar magic-leap>
    </model-viewer>

**Comment by Wulff2099** [comment] 2020-08-18 14:26
`   <model-viewer src="assets/sillon03.glb"
                  ios-src="assets/sillon01.usdz"
                  alt="Zapatillas negras tornasol"
                  shadow-intensity="1"
                  camera-controls
                  interaction-prompt="auto"
                  quick-look-browsers="safari chrome"
                  auto-rotate ar magic-leap>
    </model-viewer>`

**Comment by elalish** [comment] 2020-08-18 15:23
@Wulff2099 `ar-modes` is just another attribute, and their order doesn't matter, so you can put it anywhere in that line.

**Comment by FrankHiguera** [comment] 2020-08-18 18:56
> Okay, it looks like this was an ARCore update that broke Chrome XR; it had only partially rolled out, which I think is why some devices were working and others weren't. We've let them know and I believe it's now getting rolled back while we figure out the issue. If you have Play Services for AR v1.18, you should be fine, v1.19 seems to be problematic. Please let me know if you are still having problems or if your results don't match my description here. Thanks for the bug reports!

Hi @elalish, I can confirm that my devices (S7 and S9) that stopped working with WebXR (making a flash when pressing the AR activate button and staying in the browser without finally activating the AR) are using using Play Services for AR v1.19.202 .., BTW thanks fot your tips of using (chrome: // inspect / # devices?), This is my console log in case it helps:

Attempting to present in AR ...
Could not create a session because: Something went wrong initializing the session in the runtime
Error while trying to present to AR
DOMException: The specified session configuration is not supported.
Error while trying to end AR session
TypeError: Cannot read property 'end' of null
     at _d.stopPresenting (model-viewer.js: 1643)
     at HTMLElement. [enterARWithWebXR] (model-viewer.js: 1774)
     at async HTMLElement.activateAR (model-viewer.js: 1774)

For the moment I will set the scene-view as my primary.

**Comment by elalish** [comment] 2020-08-18 19:08
@FrankHiguera Thanks! WebXR should be working again now, though you might have to wait for the play store to update Play Services for AR (it should be queued up already). Please let me know if it's still not working.

**Comment by Wulff2099** [comment] 2020-08-19 13:26
Thanks for all the help elalish!!

**Closed** 2021-04-01 20:39 UTC
Labels: flag: not model-viewer

**Comment by sprengerst** [comment] 2021-06-01 13:08
Hi @elalish , if a device is not supporting neither WebXR nor Scene-Viewer as an example FairPhone 3. Is there any way to catch an error while clicking the AR button? So is there an AR error event or something like this?

**Comment by elalish** [comment] 2021-06-01 17:25
Unfortunately we don't get enough information back to have a great solution here, so this is the best we have: https://modelviewer.dev/docs/#entrydocs-augmentedreality-events-arStatus
