### ISSUE TITLE
Models sometime turn completely black (after initially working)

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#782] opened 2019-09-30 13:47 UTC
### Description

Every once in a while when I leave a model-viewer tab open in Safari on iOS 13, I come back to it and the whole model is black. Sometimes it also does a weird tearing effect:

![weird](https://user-images.githubusercontent.com/190692/65884496-f5b59c00-e366-11e9-8732-5bbdc04d47bc.gif)

#### Live Demo

I don't quite know what the repro steps are since it seems to happen randomly. I go here:
https://tryit.media

And then I open other tabs and come back to it some time later.

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.6.1
- three.js: r105

**Comment by cdata** [comment] 2019-09-30 17:27
I was definitely able to reproduce this by accident when I was testing iOS 13 on an iPad Pro the other day. I can confirm that it apparently happens random when switching back to the tab after a bit.

**Comment by mkeblx** [comment] 2019-10-01 22:10
I've seen the same phenomenon of rendering black after returning to page, a few times recently on on Chrome 78b Android.

**Comment by cdata** [comment] 2019-10-04 19:01
@mkeblx can you share more information about the device you are experiencing this on?

**Comment by mkeblx** [comment] 2019-10-08 01:34
It was on a Galaxy S10. I'll see if I can reproduce.

**Comment by sinlios** [comment] 2019-10-18 19:10
I'm having the exact same issue but with any model created with Microsoft Paint 3D.
It doesn't matter the browser, the render is a allways a black silouette.

**Comment by mkeblx** [comment] 2019-10-18 19:17
@sinlios Do your models initially render correctly, and the only later render black?

If they are always black then it would be a different issue. Probably specific to Paint 3D export compatibility.

**Comment by sinlios** [comment] 2019-10-18 19:25
@mkeblx you are right. The models do not initially render correctly but perhaps there is something in common as the rendering result is the same.

**Comment by pushmatrix** [comment] 2019-10-18 19:27
@sinlios Is it black using this viewer? https://model-viewer.glitch.me

**Comment by sinlios** [comment] 2019-10-18 19:33
@pushmatrix no, it works fine there

**Comment by sinlios** [comment] 2019-10-18 19:43
I'm testing some models in this sample app:
https://visualneo.com/tutorials/neo3dmodel/
The red button "Load House" reproduces the problem
This is the problematic .glb model:
https://visualneo.com/tutorials/neo3dmodel/casa-berge.glb

**Comment by sinlios** [comment] 2019-10-26 16:40
I have just tested latest version (0.7.2) and now it works fine for me with any Miscrosoft Paint3D model

**Comment by elalish** [comment] 2020-05-12 17:35
@pushmatrix Have you seen this lately? It might have been a Chrome bug, so I'd like to know if I should close it or investigate it.

**Comment by pushmatrix** [comment] 2020-05-12 17:37
@elalish I haven't seen it either. Good to close

**Comment by sprengerst** [comment] 2021-01-22 13:51
We have experienced this in Safari for Mac and on Android Chrome recently. It occurs randomly.

**Comment by elalish** [comment] 2021-01-22 17:25
@sprengerst That's concerning. Would you mind filing a new issue with all the requested version info and such? I haven't ever seen this on Chrome Android; do you have a sense of the rough frequency? If you can manage to find repro steps (even if unreliable) that would be quite helpful.

**Comment by elalish** [comment] 2021-01-22 17:26
@sprengerst nevermind, I see you did just that. Thanks!

**Comment by elalish** [comment] 2021-08-06 16:42
I randomly ran across a repro for this while I was investigating something else and I noticed the GL context had been lost (seems to happen sometimes when switching tabs/GPUs, though it's tricky to make it trigger). I realized the problem is three is fixing their side when the context gets destroyed, but we failed to do the same with our lighting.

**Closed** 2021-08-06 18:42 UTC
Labels: type: bug, arc: compatibility, arc: rendering & effects

**Comment by pushmatrix** [comment] 2021-08-09 14:45
Nice find @elalish !

**Comment by lanxinger** [comment] 2021-11-18 19:27
Actually see this is still an issue using the latest build on iOS. Both on iOS 15.1 and iPadOS 15.1. In addition on the iPad there is a major slowdown on the model once loaded. It feels it's not rendering at high frame rate that matches the display.

**Comment by rawwerks** [comment] 2022-02-19 19:06
is this the same thing or should i open a new issue?

https://user-images.githubusercontent.com/19483938/154815281-2db6b4c3-5a63-4aeb-99fb-811cb05c132d.mp4

**Comment by elalish** [comment] 2022-02-22 20:22
@rawwerks That definitely looks like a different issue; I've never seen that before. Please file a new issue and fill out the template completely so we can repro. Thanks!
