### ISSUE TITLE
Occasional low-res/pixelated/blurry models on windows

### ISSUE THREAD

**Issue by GlebVST** [google/model-viewer#3044] opened 2021-12-10 10:32 UTC
### Description

There is some semi-random issue arising on some Windows 10 machines (at least) with Chrome browser (at least). Models get rendered low-res/blurry which impacts all pages using model-viewer including examples site (!). 
This one is really tricky but has been reported by multiple users of our system utilizing model-viewer, and eventually I was able to catch this on win10 machine and grab some screenshots.

![1](https://user-images.githubusercontent.com/22114613/145554379-35cffd8a-1621-4f20-bda1-b2f22e274648.png)

* Changing browser window size, scaling up/down, reloading/refreshing page, opening in other tabs doesn't make it any better. All pages with models rendered by model-viewer look low res. 
* I checked into debugger and internal canvas has fixed width/height with no weird decimal numbers, all looks good, no errors on the console, just the model is low res. 
* No issues with performance in general, say scrolling is smooth as general, i.e. it's not a "freeze" of some sort. 

This doesn't reproduce every time and eventually gone on my test win machine after restarting chrome - could be difficult to reproduce unless using win on a frequent basis. In fact it has only reproduced after I've left the page with a model for a night and then it came out of sleep next morning (can't prove it's related though)

While the bug was "actively reproducing" I was able to fix our system using a solution from another issue #1715 i.e. setting
```
const ModelViewerElement = customElements.get('model-viewer');
ModelViewerElement.minimumRenderScale = 1;
```
but just to emphasize the model or it's root element was't moving in any sense ! 
Somehow the logic that decides on downscaling gets broken sometimes and it applies to all pages of the browser instance...

Below is a screenshot of the same model where right is a "fixed" version using `minimumRenderScale=1` approach.

![5](https://user-images.githubusercontent.com/22114613/145558085-bb5faf38-c86a-4abf-ad48-13018929c6bb.png)

So #1715 was closed long ago but the root cause looks to be there still and at least we could mention it as a "know issue" and state a workaround in documentation.

#### Live Demo

Happens on the examples site as well
https://modelviewer.dev/

### Version

- model-viewer: v1.9.1

### Browser Affected

- [x] Chrome, version: 96.0.4664
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows 10

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment] 2021-12-10 16:58
> but just to emphasize the model or it's root element was't moving in any sense !

This is the key to this being a bug and not expected behavior. I have never seen this; when this is happening, does the page still scroll very smoothly? The render scale is based on Chrome's frame rate which can be affected by anything running on the system since the GPU is  shared. Any details you can give on the system(s) where you've been able to repro this would be helpful (device & GPU make/model). 

Thanks for looking at the internal canvas, but its  width and height actually stay fixed (for performance). You'll want to look at its `style.width` and height. Those get larger as the resolution goes down. If you use the non-minified version of our library, you can search for `updateRendererScale()` and set a breakpoint  in the function where the scale changes to see exactly what's happening. You  might also try dumping `avgFrameDuration`  to  the console to see what frame rate  you seem to be getting.

**Comment by elalish** [comment] 2022-07-29 22:24
This may have been fixed by the canvas rounding PR. Either way, I can't repro.

**Closed by elalish** 2022-07-29 22:24 UTC
