### ISSUE TITLE
the model viewer is failing.

### ISSUE THREAD

**Issue by Ax-Zis** [google/model-viewer#2389] opened 2021-05-17 22:02 UTC
### Description

I want to enter from my mobile to see the objects from my camera and I get a popup saying "The object cannot be loaded, it seems that an error occurred with this object".

What can it be or does someone have the solution?
Greetings...

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment] 2021-05-17 22:32
Please fill out the whole issue template! At the very least I need a link to reproduce your problem. And screenshot or video would also be very helpful.

**Comment by Yehoyakim** [comment] 2021-05-17 23:02
maybe the same problem in #2381?

**Comment by Ax-Zis** [comment] 2021-05-18 04:42
Here is a video of what happens to me.
https://drive.google.com/file/d/1xiMqbik2cFHforBcVPUM6EijUC3g10Os/view?usp=sharing

**Comment by AndresSalomon1990** [comment] 2021-05-18 13:52
Same is happening to me. Is when using the scene-viewer ar-mode. With webxr works fine.

**Comment by elalish** [comment] 2021-05-18 17:10
I'm closing this as a dupe of #2381 so we can keep all the discussion in one place.

**Closed by elalish** 2021-05-18 17:10 UTC
