### ISSUE TITLE
Poster coverage is not seamless when aspect ratio is "more portrait" than generated poster

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1444] opened 2020-08-05 21:32 UTC
### Description

Follow up to #1428.

Poster coverage is not seamless at portrait aspect ratios. Seems the poster is scaled down to fit into viewport while the model is not scaled down, resulting in incorrect transition.

#### Live Demo
http://modelviewer.dev/editor

Create & display poster at ~square aspect
Scale page to "portrait" (e.g. 1:2)
Click on poster
Expected: seamless transition
Actual: different fit

![200805-232831](https://user-images.githubusercontent.com/2693840/89466185-a654af00-d773-11ea-8ba9-66b66931fc3f.gif)

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment] 2020-08-06 22:04
Ah yes, this is a quirk specific to the editor. It will work properly in a model-viewer element at least. I need to handle the camera updates better. FYI @stevesan

**Comment by hybridherbst** [comment] 2020-08-07 09:02
I see, should have tested better – so the issue is actually that the editor does not scale the camera aspect as it does in model-viewer when resizing?

**Comment by elalish** [comment] 2020-08-07 16:36
Yeah, basically the problem is that it keeps its own state; I need to make it use model-viewer's camera state instead.

**Comment by elalish** [comment] 2021-01-13 00:02
This was fixed a few months ago and we forgot to close the issue.

**Closed by elalish** 2021-01-13 00:02 UTC
Labels: project: editor, type: bug
