### ISSUE TITLE
WebXR on Chrome Beta

### ISSUE THREAD

**Issue by aarbro** [google/model-viewer#1039] opened 2020-02-19 19:43 UTC
### Description

Now that Chrome Beta (81) has enabled WebXR/AR without any flags, it looks to be a fairly short time before it goes into the stable build.

As of today, the [modelviewer.dev AR example](https://modelviewer.dev/examples/augmented-reality.html) doesn't work very well in Chrome 81 on Android. It doesn't give prompts and the surface placement indicator doesn't seem to show up easily. Along with this, I can't seem to scale the model (or it is not easy). 

I found issue https://github.com/google/model-viewer/issues/984 that may be tracking these problems, but I wanted to be sure.

I assume also that the "unstable-webxr" flag will still govern the use of WebXR, but I also assume that in the longer term it will become the default. Are these assumptions correct?

#### Live Demo

https://modelviewer.dev/examples/augmented-reality.html

### Browser Affected

- [x] Chrome (beta - version 81)
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android (Android 10 on Pixel 3)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.9.0
- three.js: n/a

**Comment by cdata** [comment] 2020-02-19 23:03
@aarbro broadly speaking your assumptions are all correct. We have plans to revise the whole UX of the default WebXR-based AR placement flow. We also want to do work to make that flow easy to customize, although that isn't very well defined right now.

Ultimately, the timing around this is going to depend a lot on user demand vs. the other work we have in store. Although from one perspective, we have the resources of Google at our disposal, we are actually a relatively small team and we have to carefully plan the order that we do things.

Eventually, I would say the following things will be true:

 - `unstable-webxr` attribute will go away
 - WebXR-based AR will be the default AR mode, and used where supported
 - The "order of precedence" for AR mode will be configurable (so you can tell `<model-viewer>` you prefer Scene Viewer over WebXR, for example)
 - Most or all of the UX in the WebXR-based placement mode will be customizable to some degree
 - There will be other WebXR-based AR modes besides "place a single model in front of you"

**Comment by aarbro** [comment] 2020-02-20 18:00
@cdata Thanks for the information, that gives me great info regarding direction in general.

To be a little more direct, do you expect the WebXR implementaiton of AR to more closely resemble the UX that is currently available in the scene viewer?

I see that issue 984 (which I assume is what you're tracking WebXR issues) is targeted for 1.0.0. Any idea when that might be?

**Comment by cdata** [comment] 2020-02-20 18:03
@aarbro we are currently trying to close in on v1.0.0 as soon as possible. It is scheduled as our next release. We make releases every six weeks. However: we do not guarantee the date that v1.0.0 will be released. We may move the release based on engineering prioritization decisions.

As far as WebXR-based AR UX is concerned, we intend to ship a default UX that is very similar to Scene Viewer.

**Comment by elalish** [comment] 2020-03-26 17:40
Closing as a duplicate of #984.

**Closed by elalish** 2020-03-26 17:40 UTC

**Comment by aarbro** [comment] 2020-04-13 14:25
@cdata Any update on how close you are to a 1.0 release and how it works on Chrome 81 regarding WebXR?

**Comment by cdata** [comment] 2020-04-13 15:22
@aarbro we are close to releasing v0.10.0 which will include stable support for WebXR / AR, including a new, improved UX. Look for it as early as this week!
