### ISSUE TITLE
image target for AR Mode

### ISSUE THREAD

**Issue by Arumugamhns** [google/model-viewer#1219] opened 2020-05-20 14:31 UTC
I have one business card. 
i need to show the model in AR mode by place the camera view on that business
is it possibile in model-viewer

**Comment by elalish** [comment] 2020-06-01 22:27
Not currently. I'm not aware of this being supported in either SceneViewer or QuickLook, and I don't believe there's a webXR API for image tracking yet either, but I think there has been some discussion of it. @klausw if you have anything to add here.

**Comment by elalish** [comment] 2021-10-11 22:01
Closing as a duplicate of #1516.

**Closed by elalish** 2021-10-11 22:01 UTC
Labels: type: feature
