### ISSUE TITLE
Safari Browsers Model Loading Completely Black 

### ISSUE THREAD

**Issue by memoricab** [google/model-viewer#2347] opened 2021-04-30 12:03 UTC
Hello

First of all, thank you for your effort in providing an amazing, fantastic library as an opensource. Thanks, devs, thanks google.

### Description

It reproduces in Safari randomly. There is no pattern, it occurs randomly. 

I'm a bit suspicious that Safari tries to render before the model is completely loaded - might be related to caching as well.

#### Live Demo
https://user-images.githubusercontent.com/7073672/116692498-1d4a6b80-a9c5-11eb-9b59-77f2cd2d428d.mp4

### Version
```
<model-viewer poster={resource?.posterLocation}
          camera-controls
          auto-rotate
          quick-look-browsers="safari chrome"
          ar
          magic-leap
          interaction-prompt="auto"
          ar-modes="webxr scene-viewer quick-look"
          ar-scale="auto"
          style={{
            height: "100%",
            width: "100%",
            contain: "none",
            overflow: "unset !important"
          }}
          loading="eager"
          shadow-intensity="1"
          src={resource?.androidModel?.fileLocation}
          ios-src={resource?.iosModel?.fileLocation}>
```

Model is [here](https://alphaapp-panel-uploaded-models.s3.eu-north-1.amazonaws.com/SeaCleaners/4cc3e3bd-96eb-4145-a46f-d02385fde46a/Sea_Cleaners_15k.glb)

The same black loading reproduces with [this model](https://alphaapp-panel-uploaded-models.s3.eu-north-1.amazonaws.com/companiiii/02f7adf4-413a-450f-ada0-6f14bb6f5ef5/modell%20%285%29.glb) as well. Rarely randomly. 

- model-viewer: v1.6.0

### Browser Affected
- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X ] Safari 13.1.3

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X ] MacOS Catalina version 10.15.7 - Macbook Air 2020 intel chipset
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ X] QuickLook

**Comment by elalish** [comment] 2021-05-03 16:26
I think it's also a dupe of #1622. I'm going to close this one, since we're already looking into these others.

**Closed by elalish** 2021-05-03 16:26 UTC
