### ISSUE TITLE
Need Help Hotspots are not showing on my iOS devices

### ISSUE THREAD

**Issue by sahimsakir** [google/model-viewer#3442] opened 2022-05-10 04:08 UTC
### Discussed in https://github.com/google/model-viewer/discussions/3441

<div type='discussions-op-text'>

<sup>Originally posted by **sahimsakir** May 10, 2022</sup>
Hello, I have started newly on model viewer. Recently i was working on a project where I need to add hotspots which will change my  models by clicking the element. It's Working fine on browser and android devices but unfortunately i am not getting the hotspots on iOS. Can you help me to solve this?

link: artest.nvisio.one</div>

**Comment by samaneh-kazemi** [comment] 2022-05-10 16:16
Hi, please don't cross-pos. Closing this since it's a duplicate of #3441

**Closed by samaneh-kazemi** 2022-05-10 16:16 UTC
