### ISSUE TITLE
Critical dependency

### ISSUE THREAD

**Issue by robertsLando** [google/model-viewer#4106] opened 2023-02-07 09:25 UTC
### Description

Starting from latest version webpack throws this warning

```
 warning  in ../../node_modules/@google/model-viewer/lib/three-components/TextureUtils.js
Critical dependency: the request of a dependency is an expression
```

### Version

- model-viewer: v3.0.0

### Browser Affected

- [x ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment] 2023-02-07 21:38
Dupe of #4090 and #4091 - please help us figure out the right solution in #4090.

**Closed by elalish** 2023-02-07 21:38 UTC
