### ISSUE TITLE
No lighting occasionally in Safari (mostly)

### ISSUE THREAD

**Issue by sprengerst** [google/model-viewer#1955] opened 2021-01-22 14:21 UTC
![image](https://user-images.githubusercontent.com/6854862/105501518-9babb900-5cc4-11eb-84bf-6b49985747e2.png)

Hi, we have experienced this issue sometimes on iOS Safari (14.0.1 Macbook M1 Pro) and on an Android phone (Fairphone 3 / Android 10 / Chrome).

It disappears and reappears randomly by reloading the browser tab. Also for the main "astronaut.glb" example on your example site it's the same. I tried to add directional lights to our 3D model, this addds a third state:

1.) Normal perfect evenly lit.
2.) Unlit completely black
3.) Directional lit, a little bit, our custom changes.

If you reload the browser tab you can experience the states jumping randomly. As a side fact, I read out any modelviewer details like exposure, materials, etc. They seem to be identically, so there is no correlation with a bad setting or anything like this. I think there is some problem "under the hood". 

Thanks for your help!
Stefan

**Comment by elalish** [comment] 2021-01-22 17:31
Thanks for the details; this looks like a failure to generate the PMREM from the environment light, apparently with a race condition. Can you tell me the version of Chrome and have you ever seen it repro on Android 11? Also, when you say randomly, would you say it's 10%, 25%, 50% of the time?

**Comment by sprengerst** [comment] 2021-01-22 18:21
With our Macbook Pro M1 Safari 14.0.1 it is 90%, so almost every time.But we also have a Mac here, with Safari 14.0.2 M1 Mini, where it never happens 0%. It's really hard to see a reason or pattern for this behaviour.

We never experienced this for Android 11. Only for 10. It happened 2 times in the last 2 weeks, so I would say roughly 1 %. 
I think you are right with your racing condition assumption. Is there a way to make this thing synchronous?

I'm also into software and I know how stupid and hard to reproduce this bug seems, sorry for that. 👎

**Comment by elalish** [comment] 2021-01-22 18:36
ah, so it's worse on some of Apple's new ARM chips; makes sense since we're not testing there yet. Everything in model-viewer (and web components generally) is async and for good reason. It does make debug a pain sometimes, but at least we have experience. Are you always using default lighting? Does it repro at about the same frequency with `environment-image` set to some HDR? Also, what's your model-viewer version?

**Comment by sprengerst** [comment] 2021-01-23 10:33
Our model-viewer version is  the latest 1.4.1. Yes it happens with all environments. I am not sure if it is related to the M1, because it happens on one almost every time and on the second never. I have seen some threejs Bugs looking like this. Do you think this could be related?

**Comment by csbrightside** [comment] 2021-01-25 15:54
I'm also getting this issue reliably on macOS 10.14.6 in Safari 14.0.2, never seen it happen in Android though.

The astronaut on https://modelviewer.dev loads black almost every time (~95% of the time). It has loaded extremely dark once which made me think it was the lighting.

When I look at [the neutral lighting example](https://modelviewer.dev/examples/lightingandenv/#neutralLighting) I've found that it will display solid black when neutral lighting is enabled, and be fine when it's disabled.

**Comment by elalish** [comment] 2021-01-25 17:36
@sprengerst Yes, this is very likely a three.js bug we've inherited, or somehow triggered. Can you link to any of the three.js bugs you think may be related?

**Comment by aidanwolf** [comment] 2021-02-19 18:20
Providing another example. My model is rendering correctly in Chrome, not in Safari Version 14.0 (15610.1.28.1.9, 15610)
![Screen Shot 2021-02-19 at 1 19 52 PM](https://user-images.githubusercontent.com/9259668/108544948-29bf9300-72b5-11eb-990b-6a3e15774a92.png)

**Comment by sprengerst** [comment] 2021-02-23 09:17
@elalish sorry I didn't saw your message.
Maybe this one (computeVertexNormals seemed to fix this issue):
https://discourse.threejs.org/t/texture-is-black-on-windows-but-fine-on-osx/10053

There seem to be many "unlit 3D model" or "black 3D model" threejs bugs :-/ I'm not sure what is the case here.

**Comment by elalish** [comment] 2021-02-23 19:27
@aidanwolf Can you provide the link so I can debug?

**Comment by aidanwolf** [comment] 2021-02-23 21:12
@elalish here you go [](https://opensea.io/assets/0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7/170)

it seems to work sometimes and break other times, not sure what causes the inconsistency. Maybe caching?

**Comment by elalish** [comment] 2021-02-23 22:16
@aidanwolf I think you may have forgotten to paste the link? As for inconsistency, it appears to be a race condition in Safari; I doubt it's from the network. If you find any steps that make repro more or less often, that would help. It's been notably difficult to repro on my own laptop.

**Comment by aidanwolf** [comment] 2021-03-19 06:24
@elalish hi, I ended up editing my comment with the link not sure if you saw. Any progress on this particular bug by chance?

**Comment by elalish** [comment] 2021-03-22 17:06
No; I believe you but I still can't repro on Safari. As soon as we find a decent repro we'll be able to debug.

**Comment by aidanwolf** [comment] 2021-03-22 17:16
@elalish oh I see! here's my steps to reproduce if that helps:

1) Go to https://opensea.io/assets/0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7/170
2) Refresh page

Also a video: https://streamable.com/xv8swn

**Comment by romanexceed** [comment] 2021-06-03 04:49
Is there any news about this issue?

**Comment by JakeCasey** [comment] 2021-07-27 16:12
I'm able to achieve this about 50% of the time on a 2018 Mac Mini in Safari, even on the docs site. Interestingly enough it seems to almost *never* happen on my M1 Air in Safari. If I can provide any more details/help let me know! Would love to see this fixed. Is there any way to programmatically force a re-render with the correct materials that we know of? Or at least a workaround right now? Placing lights differently?

**Comment by elalish** [comment] 2021-08-05 17:14
So, we've done a little digging and as best I can tell, this is looking like a Safari WebGL driver bug (no idea about Android, but it seems there's not much repro there anyway). Specifically, I've found the intel graphics on MacOS to be the biggest problem (though it's unclear if it's specific to that chip's driver, or if it's a general race condition that is only triggered on slower GPUs). I can see it about 20% of the time if I force my macbook Pro to use only it's integrated GPU. However, I'm pretty sure it's a deeper bug than our code because sometimes the PMREM (lighting) isn't pure black; sometimes we get these beauties: 
![image](https://user-images.githubusercontent.com/1649964/128392514-6055bc14-6aa3-4d8c-bcc4-e6b3df9f9b4d.png)
![image](https://user-images.githubusercontent.com/1649964/128392545-e4dc461f-642b-4444-b76f-19ce19e12e94.png)
And we also see brief corruption in the canvas output. All this to say, I can't fix this. 

However, there's good news! Safari 15 beta does not repro the issue (as far as we can tell). This is likely because they have finally adopted WebGL2 and so rewritten this part of their stack. So, I'm going to wait a month and then close this when Safari 15 rolls out.

**Comment by phreak** [comment] 2021-09-27 15:29
I guess this is not good news, but the problem seems to happen in Safari 15 even more often than before. I encountered this now many times working on a 3d-viewer/configurator.

**Comment by elalish** [comment] 2021-09-27 15:56
@phreak Ugh, what devices have you tested on? @mrdoob I recall you couldn't repro this on Safari 15; has it broken again?

**Comment by phreak** [comment] 2021-09-27 17:24
@elalish: I can reproduce the issue on iPhone 12 Pro | iOS 15 > Safari 15, Firefox 37, Chrome 94.0.x 😳

**Comment by elalish** [comment] 2021-09-27 18:37
Well yes, all browsers on  iOS are WebKit by requirement, so there isn't really any difference. 🙃

I've managed to repro occasionally with my SE (now that it's updated to iOS 15) on https://modelviewer.dev/examples/lightingandenv/#neutralLighting and less often on https://modelviewer.dev/examples/lightingandenv/#hdrSkyboyImage

This is troubling because it's a larger issue than what we were tracking (which was specific to generating PMREM  lighting from a  scene). This one even the emissive channel of the helmet went black, which  is independent of lighting, and  I've  also seen the lighting reflections you mention but with seemingly all black  base color. Something is going deeply wrong in their  new WebGL2  driver, but I have no idea what. We may have to  roll back to WebGL1 on iOS until they get this  fixed, despite the existing flakiness there. Ugh...

**Comment by phreak** [comment] 2021-09-27 18:59
@elalish: Thanx for pointing out, I tend to forget this (Webkit) and the explanation. With your description, I filed a report on Apple's Feedback Assistant (I think it was formerly known under "filing a radar" under pro developers).

**Comment by mrdoob** [comment] 2021-09-28 09:24
> @mrdoob I recall you couldn't repro this on Safari 15; has it broken again?

Sorry, I don't have the cycles to test this.

**Comment by phreak** [comment] 2021-10-03 08:28
@elalish: Probably good news. The issues seem resolved with the new iOS 15.0.1 update. I will further test but rendering works just fine on all examples I provided before.

**Closed** 2021-10-05 18:41 UTC
Labels: type: bug, arc: rendering & effects

**Comment by elalish** [comment] 2021-10-14 16:02
@sprengers What version of MV are you testing? We haven't done a release since this  was closed, so you'd need to test our dev pages to be getting the latest. Since these bugs are quite subtle, please post a screenshot and the device, browser, version, OS, and URL tested.

**Comment by hjeldin** [comment] 2021-10-21 12:46
Can confirm it happens on iOS 15.0.2 / iPhone 11, iPhone 12 and iPhone 12 Pro.

https://bugs.webkit.org/show_bug.cgi?id=231471 this webkit bug seems related
See also here: https://developer.apple.com/forums/thread/689071

**Comment by FRMR1** [comment] 2021-11-05 15:12
I'm getting this bug on 15.1.

**Comment by sahiljain2497** [comment] 2022-01-21 20:00
I'm getting this bug on 15.2.

**Comment by elalish** [comment] 2022-01-21 20:44
@sahiljain2497 This should be fixed (with our workaround for Safari's bug) with our newly released MV v1.10.1. Is that what you're testing? If so, please file a new issue and fill in all the details of the issue template, as it could easily be something else that looks similar.

**Comment by sahiljain2497** [comment] 2022-01-22 11:53
> @sahiljain2497 This should be fixed (with our workaround for Safari's bug) with our newly released MV v1.10.1. Is that what you're testing? If so, please file a new issue and fill in all the details of the issue template, as it could easily be something else that looks similar.

Works great with latest release. 👍
