### ISSUE TITLE
iOS Chrome and Safari Slowed Down / ios 14

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1576] opened 2020-09-30 20:44 UTC
Hello all. Im using iPhone 7 ios 14.0.1 . After I updated my phone to ios 14 my models slowed down when I try to rotate it or on auto rotate. You can see what I mean in video. Anyone having that problem with iphone 7 too ? or what could be problem? 

That is my model link (size of model 1.6mb)
https://confident-lamport-09f645.netlify.app/m1.html
Model viewer 1.1.0

ps: I also tried on Model Viwer 1.2.1

Video link
https://drive.google.com/file/d/1LX-tlZJwbLPZbf44UV5LK1Tde8Xvej1y/view?usp=sharing

### Browser Affected

- [ x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ x] Safari

**Comment by elalish** [comment] 2020-09-30 23:15
Ugh, I just updated my iPhone SE to ios 14 to check and sure enough, I can repro. Looks like some kind of Safari regression (Chrome on iOS is also forced to use Safari under the hood). It's weird too, as some models are fast and others are slow, and some slow ones seem to get faster when you zoom in (which is the opposite of normal). It's also not switching canvas properly on pages with more than one model-viewer. Would you mind filing a bug on Safari/Webkit? I'll have to see if there's a workaround in the meanwhile.

**Comment by elalish** [comment] 2022-07-29 22:44
I think this has been fixed with Safari 15.5

**Closed by elalish** 2022-07-29 22:44 UTC
Labels: type: bug
