### ISSUE TITLE
CORS issue when accessing model-viewer.js  script.

### ISSUE THREAD

**Issue by najafsikander** [google/model-viewer#944] opened 2019-12-24 05:42 UTC
### Description

From early morning today, the model viewer section uploaded on our website stopped displaying 3D models. I checked the console for debugging the issue. Turned its a CORS restriction issue. While browsing through the internet on your github forum I have seen that this has happened twice before. 

![image](https://user-images.githubusercontent.com/58502378/71395944-a2837a80-2631-11ea-9e65-3654b2122ac1.png)

### Browser Affected

- [x ] Chrome
- [x ] Edge
- [x ] Firefox
- [ ] Helios
- [ x] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by najafsikander** [comment] 2019-12-24 11:09
Hi, This issue originally mentioned in post is fixed but now there is a new issue. The poster image is exceeding out of the model viewer frame towards the right side.

![image](https://user-images.githubusercontent.com/58502378/71410552-433c5f00-265f-11ea-8909-5ad44056dc6e.png)

![image](https://user-images.githubusercontent.com/58502378/71410584-5e0ed380-265f-11ea-9996-0d4020357c37.png)

**Comment by elalish** [comment] 2019-12-27 18:18
@najafsikander Can you post a [glitch](https://model-viewer.glitch.me/) that repros your issue? In v0.8 we implemented seamless poster transitions, so the `toBlob()` method with `idealAspect=true` will give you a screenshot that will work as a poster for any aspect ratio canvas.

**Comment by cdata** [comment] 2020-01-06 17:43
@najafsikander in the URL in your screenshot, it looks like you are trying to request `google/model-viewer@1.0.0`, but we have not released a v1.0.0 yet. That might be related. Try changing that part of the URL to `google/mode-viewer@0.8.0`.

**Comment by cdata** [comment] 2020-01-22 16:30
@najafsikander can you confirm if the issue is resolved for you or not?

**Comment by elalish** [comment] 2020-01-24 23:30
@cdata This could be a dupe of #965

**Comment by elalish** [comment] 2020-02-04 16:53
I believe what was left of this issue was closed in #973.

**Closed by elalish** 2020-02-04 16:53 UTC
