### ISSUE TITLE
Quick Look auto-generated USDZ does not work on Chrome + iOS

### ISSUE THREAD

**Issue by CanerErdogan** [google/model-viewer#2507] opened 2021-06-24 13:34 UTC
### Description

Greetings, auto-generated USDZ in Quick Look does not prompt AR viewer on iOS devices if Chrome is used. Trying out with Safari works just fine. I have tried with iPhone 6S, XS Max and an iPad Pro. As live demo I linked the example in model-viewer website featuring this functionality.

I would be glad for any help :) Thank you!

#### Live Demo
https://modelviewer.dev/examples/augmentedreality/#webXR

### Version
- model-viewer: v1.7.2 to v1.7.0
### Browser Affected
- [x] Chrome, version: 87.0.4280.77 (and some others in other people's devices)
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [x] WebXR
- [x] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment] 2021-06-24 16:29
Closing as a dupe of #2449. The issue has been filed on iOS Chrome.

**Closed by elalish** 2021-06-24 16:29 UTC
