### ISSUE TITLE
Can't open a AR model on Android -> Need to update the Google Application ?

### ISSUE THREAD

**Issue by REOREV** [google/model-viewer#2517] opened 2021-06-28 08:29 UTC
### Description

Hello,
Since one week, I can't open my model in AR from Glitch on my mobile Android. 
When I load the page [https://ar-afi-arriere.glitch.me](https://ar-afi-arriere.glitch.me) on my mobile, I see the model in the viewer perfectly.
But, If I try to see the model in AR, I've a message:
"Update required
To display it in your space, update your Google application"

If I click to "Update", I can't update Google.

Do you have the same problem ?
Thank you.

#### Live Demo
https://ar-afi-arriere.glitch.me

### Version

- model-viewer: vX.X.X

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [x ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x ] WebXR
- [ x] SceneViewer
- [ ] QuickLook

**Comment by nohren** [comment] 2021-06-28 15:30
Same issue here.

**Comment by REOREV** [comment] 2021-06-28 15:32
Ok. So, it's a problem of Google :-(
I tried on IOS and no problem.

**Comment by elalish** [comment] 2021-06-28 16:04
Closing as a dupe of #2489. Please use WebXR mode or wait for the fix that's currently rolling out to ARCore.

**Closed by elalish** 2021-06-28 16:04 UTC
