### ISSUE TITLE
Improved, generalized staging for fidelity test scenarios

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#449] opened 2019-03-28 21:09 UTC
We should look into improving the conditions of our fidelity test scenarios so that we can get the most actionable, consistent feedback from them.

Recording resources worth looking into here:

 - https://masteringcgi.com.au/mastering-cgi-shader-ball/
 - https://twitter.com/jcanadagarcia/status/1009152211157442560
 - https://twitter.com/jcanadagarcia/status/1009151582292840453
 - http://casual-effects.com/data/index.html

**Comment by elalish** [comment] 2019-06-07 22:31
@cdata Is this a dupe of #309?

**Comment by cdata** [comment] 2019-06-08 00:19
No, this issue was intended to cover how we present the models in fidelity test cases to maximize the useful details of the renders. In other words, picking useful camera angles and physical environment conditions that give us a higher chance of getting useful information when reviewing rendered pixels.

**Comment by cdata** [comment] 2019-06-08 00:20
This is probably worthy of inclusion as we do #616

**Comment by elalish** [comment] 2020-03-11 00:12
I'm declaring this fixed by #672.

**Closed by elalish** 2020-03-11 00:12 UTC
Labels: arc: compatibility, arc: rendering & effects, type: chore
